name: "SavantHost"
version: "1.0.0"
slug: "savanthost"
description: "Control Savant Host Scenes from Home Assistant"
url: "https://github.com/rickyangkai/savanthost-addon"
startup: "application"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  auth_code: ""
schema:
  auth_code: str
image: "rickyangkai/savanthost-{arch}"
homeassistant: "2023.1.0"
host_network: true
